language: android

jdk:
   - oraclejdk8

#env:
#  global:
#    - ANDROID_TARGET=android-24
#    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
#    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
    - 'android-sdk-license-.+'

before_script:
  - chmod +x ./mocking.sh
  - ./mocking.sh
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
  - ./gradlew clean lint checkstyle test #connectedCheck

after_success:
  - chmod +x .buildscript/*
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages
    - maven

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
