language: android
sudo: false
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - secure: "rXSaGmYiHh3cS0QptL0wbzjOmf3kdo0WoDoGmos7p98JSZ6dEgH2keQ5sfyuE9nvJsT8jZRnV8X8d3iBG2kCpgmToVcOQ/NVHj36A/BIxlXQLE2HggOaH1S08BlS3qpFgI1kwv/2nQEVSlqfo1MyTg1YE4jq6ISd7OezKi598MgyMLOHgIS+EHfUJm5FzNBPxVMEKn/pn92MktDs+swk0N//ewof8d0eylVIXvelj6hT9oKyGGgaaQyvuUvwYk7Yn3gnDais0drOEqzbCQQUj+ufQW/hKN17KYZfZ2gWF75WyBXtYp1iHEZCAFwDoBOU85MT6ciBq32pPISDU2aPFOA3UwVqvXh9MOECBJRMFGAf41gcErvWbe3I5CulYhxsqpwQeFIC80kJ7ih0QFZty2OSxtLgL1gaNFUoyZky3qh3/iahd/TAtIj4V/Mu1+zrQmW/T3Zx/HXBruBIksi/qFM5LiSEMjEZ0TwZ/aXGU6wj5rb6tOii5eVUunIh96HAYqieSGeeno0svI9pVtm7l5hpG3N+FyPuTOf9WPRwrpblRETiYnBf6O0KdrgrOAeMcme+TQtldIOgBUqNs5Hmv55DsRt1ZvIkvTTD8uBX1zBjf9qpqS18wKQGYglbhBdIyWMKQibrvCOjfpnCHrtW3jOSW+xgg59HML7JLpFPXiI="
    - secure: "jLnLGtjL+y0nD3IVJX4otdzUuqN2jPfDLNtWHn8N7SLsA+B3ImMpWrqRUqY4elhDEL4Esesq20x+W7HFtQuqNlhlMVR3X+CjKPkZN7XEzQ/fBYXB/nbi3lHdEfGR7Fn6POTGtYkprR9pgHcNBf3z9fVNasPwwnPk6VMz25MgYNFjy6p7k9R46yM5GLSMdqHHBiPTYNHIRVhjOXiyFiaemQBnMPITDMuS/uyT3joZWQdaIn5s6CGmzMaQpFZWmSnDzWq0zaSZj/QJqRf4k324ZvqOYxSScHtgldLYMxHTjBULjbykLLrYs2gMqjUnahr73ZjqESwXXb6DML64l7hmpbBTJxiX9QZpYYxhiOlPaEo/U6DI0HYybdUFpyvbMs/fDRYwLPv2Lk0kMTsPoog16KGhupStkLL5nPLekhmLDzXBH1ErpgGb1xsHCUkVgtxslKo1iYTlKZ4dePFAT6H236P658iC1rOq0oNB1V2sAJ9Sx8m/TPJA73ld0c1F9Iv/IDTLESZmlDeI8Y7qtumAjixluLfRZjFYUBmTUbhvyxxN0mwrutFw6HGRbBrxiGt1wwJ0q8DBXe7E6OomNoioLM65r4dID912gCNyWMSWy/pfFrpU7m+tIGM0idJkvShqptvMBeyX44O4/c1QXoxlbN7twUllHNYSU4HXefYZhSA="

branches:
  except:
    - gh-pages
    - maven

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-22
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
    - 'android-sdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#addons:
#  apt_packages:
#    - pandoc
#  artifacts:
#    paths:
#      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_install:
  - pip install --user codecov

before_script:
  - chmod +x ./mocking.sh
  - ./mocking.sh
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew test assembleDevDebugAndroidTest -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedDevDebugAndroidTest -PdisablePreDex --continue --stacktrace
  - rm -f $HOME/.gradle/caches/3.3/plugin-resolution/cache.properties.lock

after_success:
  - ./gradlew hyber:jacocoTestDebugUnitTestReport example:jacocoTestDevDebugUnitTestReport -PdisablePreDex --continue --stacktrace
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_snapshot.sh

#after_failure:
#  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

#after_script:
#  # print lint results details
#  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
#  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done

notifications:
  email: true
  slack:
    secure: itDbZ1a4sr2qD54H/r88wuyAT6YBpLnwtItPlifB0nDoBF/lh0FW/000X+Lyd8r+J/qj9Yhid6JbYOAa1MsT8f0oD6O36r8jjy6aWcEyp+S/oCwzDOqqH2dhrzAEeoPqcYNpZQOhvMIi96aSwZS3/cRQ2KkBXirV2NLY7L20KtfrFb4qJ/W8RjYpQFRmYVr4ToFdkcQW39HhXl02ueeuai7VLxOy/J472xik5rZKZcW7YlAqiOj5VjDNTex6Y55xOCT0r3RapTL/9DxVW1TKimzTCS713ZIMP7u9ZHflZyY2VRekZcIvLpZynowCC4qkCwqu1daFPWkjPvvJCAr0D2GekyZqiE5+Gxm2ALHxGH+A+vgwdZ11nwxGACU+kpBnGFk2dWMiK6b8HzLKYpb7j61ciBdqmjL/64GLXFVSZaaun7a/+1AWEZMskMYGyuLdJesEUdixkx0YosW46bGb/ykNogPqvbbpOSMybGT87Rr5H0/f2Hw8iRhCWWtoPUAagOlwLmnBM6HlAkrCJ+U6xbM9EH1LaRfMoBUajgJHRGdKSxvCUfXenMAWrSC8m9Al9iD/3ISSBCAX72zCp5OXMO/+Vd7bEaP/nUYnSn3CCjWb1AjEnmGycof9qiOzp07mh6/FrCqF2Tyw6/gLdVvDQbIyoGYoysWJiSTO8LgnMqw=
